[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
target-version =  ['py36', 'py37', 'py38', 'py39']
include = '''
^/(
    setup.py
    | src/plotman/.*\.pyi?
)$
'''
